const PAPERS = [
  { id:1,title:'Transparent AI Attribution in Clinical NLP',authors:['Dr. Leila Kerr'],journal:'Nature Med. Informatics',journalId:1,field:'Health Sciences',year:2024,doi:'10.4012/edin.2024.001',human:42,assisted:36,generated:22,repro:82,integrity:87,oa:true,abstract:'We benchmark AI attribution techniques in clinical NLP.',sections:[{name:'Abstract',human:40,assisted:40,generated:20},{name:'Introduction',human:45,assisted:35,generated:20},{name:'Methods',human:55,assisted:30,generated:15},{name:'Results',human:35,assisted:35,generated:30},{name:'Discussion',human:42,assisted:36,generated:22},{name:'References',human:70,assisted:20,generated:10}]},
  { id:2,title:'Reproducible LLM Workflows for Biology',authors:['Dr. Bayo Adeyemi'],journal:'PLOS Computational Biology',journalId:2,field:'Biology',year:2023,doi:'10.4012/edin.2023.022',human:48,assisted:34,generated:18,repro:89,integrity:91,oa:true,abstract:'Pipeline patterns for reproducible LLM usage in wet-lab reporting.',sections:[{name:'Abstract',human:52,assisted:30,generated:18},{name:'Introduction',human:50,assisted:32,generated:18},{name:'Methods',human:58,assisted:30,generated:12},{name:'Results',human:44,assisted:35,generated:21},{name:'Discussion',human:46,assisted:36,generated:18},{name:'References',human:72,assisted:18,generated:10}]},
  { id:3,title:'Climate Forecasting with Hybrid AI Models',authors:['Dr. Kwame Okonkwo'],journal:'Earth Systems AI',journalId:3,field:'Earth Sciences',year:2022,doi:'10.4012/edin.2022.019',human:53,assisted:30,generated:17,repro:78,integrity:83,oa:false,abstract:'Hybrid AI models improve long-horizon climate forecast robustness.',sections:[{name:'Abstract',human:51,assisted:31,generated:18},{name:'Introduction',human:56,assisted:28,generated:16},{name:'Methods',human:61,assisted:26,generated:13},{name:'Results',human:49,assisted:31,generated:20},{name:'Discussion',human:52,assisted:30,generated:18},{name:'References',human:74,assisted:16,generated:10}]},
  { id:4,title:'AI Disclosure Standards in Social Sciences',authors:['Prof. Elias Khan'],journal:'Scientometrics',journalId:4,field:'Social Sciences',year:2024,doi:'10.4012/edin.2024.041',human:60,assisted:28,generated:12,repro:75,integrity:88,oa:true,abstract:'A policy-oriented framework for disclosure standards.',sections:[{name:'Abstract',human:63,assisted:25,generated:12},{name:'Introduction',human:65,assisted:23,generated:12},{name:'Methods',human:62,assisted:25,generated:13},{name:'Results',human:58,assisted:30,generated:12},{name:'Discussion',human:60,assisted:28,generated:12},{name:'References',human:78,assisted:14,generated:8}]},
  { id:5,title:'Neuroscience Signal Integrity under AI Assistance',authors:['Dr. Nia Cole'],journal:'NeuroImage',journalId:5,field:'Neuroscience',year:2024,doi:'10.4012/edin.2024.056',human:44,assisted:38,generated:18,repro:80,integrity:85,oa:true,abstract:'Integrity metrics for AI-augmented imaging pipelines.',sections:[{name:'Abstract',human:46,assisted:36,generated:18},{name:'Introduction',human:45,assisted:37,generated:18},{name:'Methods',human:48,assisted:36,generated:16},{name:'Results',human:40,assisted:40,generated:20},{name:'Discussion',human:43,assisted:39,generated:18},{name:'References',human:68,assisted:22,generated:10}]},
  { id:6,title:'Engineering QA Systems with AI Co-Authors',authors:['Dr. Lara Mensah'],journal:'Engineering Intelligence',journalId:6,field:'Engineering',year:2023,doi:'10.4012/edin.2023.063',human:34,assisted:39,generated:27,repro:73,integrity:79,oa:false,abstract:'Engineering quality assurance in mixed human-AI authoring teams.',sections:[{name:'Abstract',human:35,assisted:38,generated:27},{name:'Introduction',human:36,assisted:37,generated:27},{name:'Methods',human:39,assisted:38,generated:23},{name:'Results',human:30,assisted:40,generated:30},{name:'Discussion',human:33,assisted:40,generated:27},{name:'References',human:64,assisted:24,generated:12}]},
  { id:7,title:'Ethics of Attribution in Foundation Models',authors:['Dr. Mei Lin'],journal:'AI & Society',journalId:7,field:'Ethics',year:2022,doi:'10.4012/edin.2022.077',human:67,assisted:22,generated:11,repro:86,integrity:93,oa:true,abstract:'Ethical framing and attribution guidance for high-impact AI outputs.',sections:[{name:'Abstract',human:69,assisted:20,generated:11},{name:'Introduction',human:70,assisted:19,generated:11},{name:'Methods',human:66,assisted:24,generated:10},{name:'Results',human:64,assisted:25,generated:11},{name:'Discussion',human:67,assisted:22,generated:11},{name:'References',human:82,assisted:12,generated:6}]},
  { id:8,title:'Institutional AI Governance in Universities',authors:['Dr. Omar Noor'],journal:'Higher Ed Analytics',journalId:8,field:'Computer Science',year:2024,doi:'10.4012/edin.2024.088',human:38,assisted:36,generated:26,repro:77,integrity:84,oa:true,abstract:'Governance controls for university-wide AI research deployment.',sections:[{name:'Abstract',human:40,assisted:34,generated:26},{name:'Introduction',human:39,assisted:35,generated:26},{name:'Methods',human:44,assisted:34,generated:22},{name:'Results',human:35,assisted:37,generated:28},{name:'Discussion',human:37,assisted:37,generated:26},{name:'References',human:66,assisted:22,generated:12}]}
];

const JOURNALS = [
  {id:1,name:'Nature Med. Informatics',publisher:'Nature',field:'Health Sciences',issn:'2673-8891',impact:24.5,avgAI:38,avgRepro:82,avgInteg:87,totalPapers:1204},
  {id:2,name:'PLOS Computational Biology',publisher:'PLOS',field:'Biology',issn:'1553-7358',impact:3.8,avgAI:42,avgRepro:89,avgInteg:91,totalPapers:985},
  {id:3,name:'Earth Systems AI',publisher:'Elsevier',field:'Earth Sciences',issn:'2212-9820',impact:5.4,avgAI:33,avgRepro:78,avgInteg:83,totalPapers:640},
  {id:4,name:'Scientometrics',publisher:'Springer',field:'Social Sciences',issn:'0138-9130',impact:3.6,avgAI:29,avgRepro:75,avgInteg:88,totalPapers:772},
  {id:5,name:'NeuroImage',publisher:'Elsevier',field:'Neuroscience',issn:'1053-8119',impact:5.7,avgAI:46,avgRepro:80,avgInteg:85,totalPapers:560},
  {id:6,name:'Engineering Intelligence',publisher:'IEEE',field:'Engineering',issn:'2243-8830',impact:4.1,avgAI:55,avgRepro:73,avgInteg:79,totalPapers:455},
  {id:7,name:'AI & Society',publisher:'Springer',field:'Ethics',issn:'0951-5666',impact:4.3,avgAI:18,avgRepro:86,avgInteg:93,totalPapers:320},
  {id:8,name:'Higher Ed Analytics',publisher:'Taylor & Francis',field:'Computer Science',issn:'2444-0021',impact:4.8,avgAI:68,avgRepro:77,avgInteg:84,totalPapers:610},
];

const AUTHORS = [
  {id:1,name:'Dr. Leila Kerr',affil:'University of Lagos',initials:'LK',orcid:'0000-0002-1010-1200',field:'Health Sciences',papers:34,citations:1240,hindex:19,avgAI:38,region:'Africa',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[21,24,27,30,33,36,38]},
  {id:2,name:'Dr. Bayo Adeyemi',affil:'Obafemi Awolowo University',initials:'BA',orcid:'0000-0003-1100-3300',field:'Biology',papers:28,citations:980,hindex:16,avgAI:42,region:'Africa',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[18,22,25,30,33,38,42]},
  {id:3,name:'Dr. Kwame Okonkwo',affil:'University of Lagos',initials:'KO',orcid:'0000-0001-2200-8877',field:'Earth Sciences',papers:24,citations:870,hindex:14,avgAI:33,region:'Africa',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[12,16,20,24,27,30,33]},
  {id:4,name:'Prof. Elias Khan',affil:'Oxford Future Lab',initials:'EK',orcid:'0000-0004-7777-9900',field:'Social Sciences',papers:41,citations:2100,hindex:27,avgAI:29,region:'Europe',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[10,13,17,21,23,26,29]},
  {id:5,name:'Dr. Nia Cole',affil:'ETH Zurich',initials:'NC',orcid:'0000-0004-0000-1001',field:'Neuroscience',papers:30,citations:1420,hindex:20,avgAI:46,region:'Europe',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[19,24,27,31,36,41,46]},
  {id:6,name:'Dr. Lara Mensah',affil:'MIT Media Lab',initials:'LM',orcid:'0000-0009-0032-2024',field:'Engineering',papers:22,citations:760,hindex:13,avgAI:55,region:'Americas',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[22,27,31,36,42,49,55]},
  {id:7,name:'Dr. Mei Lin',affil:'NUS',initials:'ML',orcid:'0000-0001-0101-0101',field:'Ethics',papers:26,citations:1120,hindex:17,avgAI:18,region:'Asia',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[9,11,13,14,15,17,18]},
  {id:8,name:'Dr. Omar Noor',affil:'Stanford AI Hub',initials:'ON',orcid:'0000-0008-4400-5500',field:'Computer Science',papers:37,citations:1660,hindex:22,avgAI:68,region:'Americas',years:[2018,2019,2020,2021,2022,2023,2024],aiByYear:[24,30,36,44,52,60,68]},
];

const state = { page:'home', query:'', discipline:'', year:'', minRepro:0 };
const $ = (s) => document.querySelector(s);
const $$ = (s) => [...document.querySelectorAll(s)];

function showToast(msg){const r=$('#toastRegion');const el=document.createElement('div');el.className='toast';el.textContent=msg;r.appendChild(el);requestAnimationFrame(()=>el.classList.add('show'));setTimeout(()=>{el.classList.remove('show');setTimeout(()=>el.remove(),250)},3000)}
function navigate(page){state.page=page;$$('.page').forEach(p=>p.classList.remove('active'));$(`#page-${page}`).classList.add('active');$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===page));$('#main-wrap').scrollTo({top:0,behavior:'smooth'});if(window.innerWidth<768)$('#sidebar').classList.remove('open')}
function aiChip(pct){const c=pct<25?'var(--blue)':pct<40?'var(--yellow)':pct<60?'var(--orange)':'var(--red)';return `<span style="padding:2px 8px;border-radius:99px;background:var(--bg-3);font-family:'DM Mono';color:${c}">${pct}%</span>`}
function stackedBar(p){return `<div style='display:flex;height:8px;border-radius:4px;overflow:hidden;background:var(--bg-3)'><div style='width:${p.human}%;background:var(--green)'></div><div style='width:${p.assisted}%;background:var(--yellow)'></div><div style='width:${p.generated}%;background:var(--orange)'></div></div>`}

function renderHome(){
  const items=[['Papers Indexed','4.28M','+12% this month'],['Journals Covered','18,420','+340 new'],['AI-Verified Papers','1.92M','+28% YoY'],['Indexed Authors','2.9M','+180K new']];
  $('#kpiGrid').innerHTML=items.map(([l,v,c],i)=>`<div class='kpi-card'><div class='kpi-label'>${l}</div><div class='kpi-val' id='kpi-${i}'>0</div><div class='kpi-change'>${c}</div></div>`).join('');
  animateCounts([4280000,18420,1920000,2900000]);
  const fields=[['Health Sciences',42],['Computer Science',68],['Biology',38],['Social Sciences',29],['Earth Sciences',33],['Neuroscience',46],['Ethics',18],['Engineering',55]];
  $('#disciplineBars').innerHTML=fields.map(([f,v])=>`<div class='bar' style='height:${v}%' data-term='${f}' tabindex='0'><small>${f.split(' ')[0]} ${v}%</small></div>`).join('');
  $('#fieldExplorer').innerHTML=fields.map(([f,v])=>`<div class='field-card' data-term='${f}'><b>${f}</b><div style='font-size:11px;color:var(--text-muted)'>${v}% AI</div></div>`).join('');
  $('#recentBody').innerHTML=PAPERS.slice(0,5).map(p=>`<tr data-id='${p.id}'><td><span class='click'>${p.title}</span></td><td>${p.authors.join(', ')}</td><td>${p.journal}<div style='font-size:10px;color:var(--text-dim)'>${p.year}</div></td><td>${stackedBar(p)}</td><td>${p.repro}</td><td>${p.integrity}</td></tr>`).join('');
}
function filterPapers(){return PAPERS.filter(p=>{const q=(p.title+p.authors.join(' ')+p.journal+p.field).toLowerCase().includes(state.query.toLowerCase());const d=!state.discipline||p.field===state.discipline;const y=!state.year||String(p.year)===String(state.year);const r=p.repro>=state.minRepro;return q&&d&&y&&r;})}
function renderSearch(){const data=filterPapers();$('#searchCount').textContent=`(${data.length})`;$('#searchBody').innerHTML=data.map(p=>`<tr data-id='${p.id}'><td><span class='click'>${p.title}</span></td><td>${p.authors.join(', ')}</td><td>${p.field}</td><td>${p.year}</td><td>${aiChip(p.generated)}</td><td>${p.repro}</td><td>${p.integrity}</td></tr>`).join('');const avg=(k)=>Math.round(data.reduce((a,b)=>a+b[k],0)/(data.length||1));$('#quickStats').innerHTML=`Avg AI Generated: ${avg('generated')}%<br>Avg Repro: ${avg('repro')}<br>Avg Integrity: ${avg('integrity')}`}
function renderSources(){$('#journalBody').innerHTML=JOURNALS.map(j=>`<tr><td>${j.name}<div style='font-size:10px;color:var(--text-dim);font-family:"DM Mono"'>${j.issn}</div></td><td>${j.publisher}</td><td>${j.field}</td><td style='font-family:"DM Mono"'>${j.impact}</td><td>${aiChip(j.avgAI)}</td></tr>`).join('')}
function renderAuthors(){$('#authorsGrid').innerHTML=AUTHORS.map(a=>`<article class='author-card' data-author='${a.id}' tabindex='0'><div style='display:flex;gap:8px;align-items:center'><div style='width:44px;height:44px;border-radius:12px;background:linear-gradient(135deg,var(--accent-dim),rgba(62,207,142,.1));display:grid;place-items:center;font:800 14px Syne;color:var(--accent)'>${a.initials}</div><div><b>${a.name}</b><div style='font-size:11px;color:var(--text-muted)'>${a.affil}</div></div></div><div style='margin-top:8px;font-size:11px;color:var(--text-muted)'>${a.field} · h-index ${a.hindex} · Avg AI ${a.avgAI}%</div></article>`).join('')}
function renderDash(){$('#dashGrid').innerHTML=[['Total Publications','1,284','+14% YoY'],['AI-Verified Papers','847','+42% YoY'],['Avg Integrity Score','82.4','+3.1 pts'],['Active Researchers','318','+28 new']].map(x=>`<div class='kpi-card'><div class='kpi-label'>${x[0]}</div><div class='kpi-val'>${x[1]}</div><div class='kpi-change'>${x[2]}</div></div>`).join('')}
function doSearch(term){state.query=term||$('#topSearch').value||$('#heroSearch').value||'';navigate('search');renderSearch()}
function animateCounts(targets){targets.forEach((t,i)=>{const el=$(`#kpi-${i}`);let s=0;const st=performance.now();const dur=1400;function tick(n){const p=Math.min((n-st)/dur,1);const e=1-Math.pow(1-p,3);const v=Math.floor(s+(t-s)*e);el.textContent=t>1000000?(v/1000000).toFixed(2)+'M':v.toLocaleString();if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)})}
function openPaper(id){const p=PAPERS.find(x=>x.id===id);if(!p)return;showToast(`${p.title} — ${p.journal} (${p.year}) · DOI ${p.doi}`)}

function init(){
  $('#filterDiscipline').innerHTML='<option value="">All Fields</option>'+[...new Set(PAPERS.map(p=>p.field))].map(f=>`<option>${f}</option>`).join('');
  $('#filterYear').innerHTML='<option value="">Any Year</option>'+[...new Set(PAPERS.map(p=>p.year))].map(y=>`<option>${y}</option>`).join('');
  renderHome();renderSearch();renderSources();renderAuthors();renderDash();

  $$('.nav-item').forEach(n=>n.addEventListener('click',()=>n.dataset.page&&navigate(n.dataset.page)));
  $('#topSearch').addEventListener('keydown',e=>e.key==='Enter'&&doSearch());
  $('#heroSearchBtn').addEventListener('click',()=>doSearch());
  $('#heroSearch').addEventListener('keydown',e=>e.key==='Enter'&&doSearch());
  document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#topSearch').focus()}});
  document.body.addEventListener('click',e=>{const t=e.target.closest('[data-term]');if(t)doSearch(t.dataset.term);const row=e.target.closest('tr[data-id]');if(row)openPaper(Number(row.dataset.id));const a=e.target.closest('[data-author]');if(a){const x=AUTHORS.find(i=>i.id===Number(a.dataset.author));showToast(`${x.name} · ${x.affil} · ${x.papers} papers`)}});
  $('#filterDiscipline').addEventListener('change',e=>{state.discipline=e.target.value;renderSearch()});
  $('#filterYear').addEventListener('change',e=>{state.year=e.target.value;renderSearch()});
  $('#reproRange').addEventListener('input',e=>{state.minRepro=Number(e.target.value);$('#reproOut').textContent=state.minRepro;renderSearch()});
  $('#sidebarToggle').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
  setInterval(()=>{$('#liveTicker').textContent=`● Live Index — ${(4.28 + Math.random()*0.01).toFixed(2)}M Papers Indexed`},8000);
}

document.addEventListener('DOMContentLoaded',init);
